const landscape = "landscape";
module.exports = [
  {
    filename: "raw_img/attractions/beef_king_of_meats.jpg",
    alt: "",
    landscape,
    rowSpan: 1,
    colSpan: 1,
    width: '300',
  },
  {
    filename: "raw_img/attractions/carhenge copy.jpeg",
    alt: "",
    landscape,
    rowSpan: 1,
    colSpan: 2,
    width: '800',
  },
  {
    filename: "raw_img/attractions/cassey_toilets.jpg",
    alt: "",
    landscape,
    rowSpan: 1,
    colSpan: 2,
    width: '600',
  },
  {
    filename: "raw_img/attractions/carhenge_josh.jpg",
    alt: "",
    rowSpan: 2,
    colSpan: 1,
    width: '300',
  },
  {
    filename: "raw_img/attractions/carhenge_loves.jpg",
    alt: "",
    landscape,
    rowSpan: 2,
    colSpan: 2,
    width: '600',
  },
  {
    filename: "raw_img/attractions/cars_cars.jpg",
    alt: "",
    landscape,
    rowSpan: 1,
    colSpan: 2,
    width: '400',
  },
  {
    filename: "raw_img/attractions/classic_head.jpg",
    alt: "",
    rowSpan: 1,
    colSpan: 1,
    width: '300',
  },
  {
    filename: "raw_img/attractions/capitol.jpg",
    alt: "",
    rowSpan: 1,
    colSpan: 2,
    width: '600',
  },
  {
    filename: "raw_img/attractions/clay-sculptures.jpg",
    alt: "",
    rowSpan: 1,
    colSpan: 1,
    width: '400',
  },
  {
    filename: "raw_img/attractions/hbd_big_jeff.jpg",
    alt: "",
    rowSpan: 1,
    colSpan: 1,
    width: '300',
  },
  {
    filename: "raw_img/attractions/modern_tv.jpg",
    alt: "",
    rowSpan: 1,
    colSpan: 1,
    width: '300',
  },
  {
    filename: "raw_img/attractions/ravenna.jpg",
    alt: "",
    landscape,
    rowSpan: 1,
    colSpan: 2,
    width: '600',
  },
  {
    filename: "raw_img/attractions/thinking about carhenge copy.jpg",
    alt: "",
    landscape,
    rowSpan: 1,
    colSpan: 1,
    width: '600',
  },
  {
    filename: "raw_img/attractions/windmills.jpg",
    alt: "",
    landscape,
    rowSpan: 1,
    colSpan: 3,
    width: '600',
  },
  {
    filename: "raw_img/attractions/veggies.png",
    alt: "",
    rowSpan: 1,
    colSpan: 2,
    width: '600',
  },
];
