module.exports = [
    {
        name: "Queer: A Graphic History",
        author: "Meg-John Barker",
        tags: ["graphical", "nonfiction", "queer", "favorites"],
        img: "queer-history.jpg", 
    },
    {
        name: "Hench",
        author: "Natalie Zina Walschots",
        tags: ["sci fi/fantasy", "fiction", "favorites"],
        img: "hench.jpg", 
    },
    {
        name: "A Prayer for the Crown-Shy",
        author: "Becky Chambers",
        tags: ["sci fi/fantasy", "fiction", "queer"],
        img: "prayer.jpg", 
    },
    {
        name: "When Women Were Dragons",
        author: "Kelly Barnhill",
        tags: ["sci fi/fantasy", "fiction", "queer", "favorites"],
        img: "dragons.jpg", 
    },
    {
        name: "Cemetery Boys",
        author: "Aiden Thomas",
        tags: ["sci fi/fantasy", "fiction", "queer"],
        img: "cemetery.jpg",
    },
    {
        name: "Upright Women Wanted",
        author: "Sarah Gailey",
        tags: ["fiction", "queer"],
        img: "upright.jpg",
    },
    {
        name: "Uprooted",
        author: "Naomi Novik",
        tags: ["sci fi/fantasy", "fiction"],
        img: "uprooted.jpg", 
    },
    {
        name: "Payback's a Witch",
        author: "Lana Harper",
        tags: ["sci fi/fantasy", "fiction", "queer"],
        img: "payback.jpg",
    },
    {
        name: "Ace",
        author: "Angela Chen",
        tags: ["queer", "nonfiction", "favorites"],
        img: "ace.jpg", 
    },
    {
        name: "The Art of Gathering: How We Meet and Why It Matters",
        author: "Priya Parker",
        tags: ["nonfiction", "favorites"],
        img: "gathering.jpg", 
    },
    {
        name: "A Spindle Splintered",
        author: "Alix Harrow",
        tags: ["sci fi/fantasy", "fiction"],
        img: "spindle.jpg",
    },
    {
        name: "Matrix",
        author: "Lauren Groff",
        tags: ["fiction", "queer"],
        img: "matrix.jpg",
    },
    {
        name: "The Third Person",
        author: "Emma Grove",
        tags: ["graphical", "nonfiction", "queer"],
        img: "third_person.jpg", 
    },
    {
        name: "Solutions and Other Problems",
        author: "Allie Brosh",
        tags: ["graphical", "nonfiction"],
        img: "solutions.jpg", 
    },
    {
        name: "Essential Labor: Mothering as Social Change",
        author: "Angela Garbes",
        tags: ["nonfiction"],
        img: "essential.jpg", 
    },
    {
        name: "Everyday Vitality",
        author: "Kate Mangino",
        tags: ["nonfiction"],
        img: "everyday.jpg", 
    },
    {
        name: "Let's Get Physical",
        author: "Danielle Friedman",
        tags: ["nonfiction"],
        img: "physical.jpg", 
    },
    {
        name: "Guapa",
        author: "Saleem Haddad",
        tags: ["queer", "fiction"],
        img: "guapa.jpg", 
    },
    {
        name: "Girlhood",
        author: "Melissa Febos",
        tags: ["nonfiction", "queer"],
        img: "girlhood.jpg",
    },
];